name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Dockersab
        run: sudo docker pull ericsb888/playinperson:latest
      - name: Delete old docker container
        run: docker rm -f playinperson || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name playinperson ericsb888/playinperson
