name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker
        run: sudo docker pull ericsb888/playinperson:latest
      - name: Stop Docker
        run: docker stop playinperson || true
      - name: Delete old docker container
        run: docker rm -f playinperson || true

      - name: Run Docker Containers
        run: sudo docker run -d -p 80:8080 --name playinperson ericsb888/playinperson
